# Generated by Django 4.1.6 on 2023-02-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='empdet',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='empimg',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='place',
            name='empname',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
